### ISSUE TITLE
Errors while saving single-file

### ISSUE THREAD

**Issue by Marxsal** [Arlen22/TiddlyServer#59] opened 2019-04-19 02:54 UTC
# Edit: This is for 2.1.1-beta

Making a change to a tiddler on a single file doesn't change the "saved" checkmark, though it appears that it is saving. But making a second change, I get 

Error while saving:
XMLHttpRequest error code: 0

and
XMLHttpRequest error code: 412

Errors.

**Comment by Arlen22** [comment] 2019-04-20 01:22
What server logs show up for this one?

**Comment by Marxsal** [comment] 2019-04-20 03:19
The first time you create a tiddler, there's nothing remarkable in the log. The checkmark stays red. Nothing appears to be saving. The 2nd time you create a tiddler, there's something about etags... 

-------

[2019-04-19T20:15:39.796-0700] GET     127.0.0.1       200 127.0.0.1 /Wikis/note
s/notes.html                                     245.136 ms - 3816451
[2019-04-19T20:15:40.008-0700] OPTIONS 127.0.0.1       200 127.0.0.1 /Wikis/note
s/notes.html                                     14.869 ms - 20
[2019-04-19T20:15:40.011-0700] HEAD    127.0.0.1       304 127.0.0.1 /Wikis/note
s/notes.html                                     15.308 ms - -
[2019-04-19T20:15:40.494-0700] GET                     - 127.0.0.1 /Wikis/notes/
favicon.ico                                    - ms - -
412 ifmatch "0-3816451-1555644827000"
412 etag "0-3816602-1555644827000"
412 caused by difference in size
[2019-04-19T20:17:24.897-0700] PUT     127.0.0.1       412 127.0.0.1 /Wikis/note
s/notes.html                                     48.716 ms - -

**Comment by Marxsal** [comment] 2019-04-20 03:21
I should have mentioned -- this is 2.1.1-beta.

**Comment by Arlen22** [comment] 2019-04-21 02:21
For some reason the file size changed while the file was being edited. Each time it saves it records the file size in an etag and sends it back to the browser. The browser sends the last etag on every save, and if the file size on disk has changed since the last save, the server rejects the browser's save request. This is to prevent edits from overwriting each other, such as when you are working on two computers at the same time. Single file wikis are saved per-wiki, not per-tiddler, so adding a new tiddler on one computer, and then adding a new tiddler on a second computer without first reloading the page to load the first tiddler would actually cause the first tiddler to be lost.

**Comment by Marxsal** [comment] 2019-04-21 02:36
But the error happens every time I run with 2.1.1-beta. It doesn't happen at all if I run with the old version (sorry, I don't know what version it is -- is there a way to tell? It was installed in July 2018.)

**Comment by Arlen22** [comment] 2019-04-22 15:40
I will check this out. I don't know why, but your log indicates the file size is different, which should not be happening. Can you verify that this behavior happens with an empty wiki from this link: https://tiddlywiki.com/empty.html (right click and save as to download).

**Comment by Marxsal** [comment] 2019-04-22 15:58
Yes, it happens with an empty. I will add, in the interest of full-disclosure, that I'm running on top of a drive mapped by cryptomator. However, the save works fine when running the old TS (sometime in July 2018), so it it's not about the file system. So, unless the file check thing is new? Maybe the old TS didn't do the check so wouldn't notice a change?

**Comment by Marxsal** [comment] 2019-04-22 16:52
Ok, I tested on the native file system (windows NTFS) and the same error occurs. So it's something in the new beta.

**Comment by MaruKob** [comment] 2019-05-08 08:00
Hi Arlen22

i have the same problem. it seems, that after a change, the new file is writting but the browser not reload the new wiki.

If i make a change and press the reload button every time after this, is there no error.
Without a reload after changes, the error is every time i edit a tiddler again and close the tiddler.

Tested with firefox 67 and Chrome and new empty.htm.

I stand by for testing ;)

**Comment by MaruKob** [comment] 2019-05-08 08:20
Log:

Open your browser and type in one of the following:
http://127.0.0.1:8080
[]
[2019-05-08T10:19:29.821+-200] GET     127.0.0.1       200 127.0.0.1 /                                                           11.247 ms - 9205
[2019-05-08T10:19:29.849+-200] GET     127.0.0.1       304 127.0.0.1 /directory.css                                              2.173 ms - -
[2019-05-08T10:19:29.850+-200] GET     127.0.0.1       304 127.0.0.1 /assets/icons/files/htmlfile.png                            0.779 ms - -
[2019-05-08T10:19:29.851+-200] GET     127.0.0.1       304 127.0.0.1 /assets/icons/folder.png                                    0.649 ms - -
[]
[2019-05-08T10:19:34.062+-200] GET     127.0.0.1       200 127.0.0.1 /empty.html                                                 4.136 ms - 2168427
[]
[2019-05-08T10:19:34.208+-200] OPTIONS 127.0.0.1       200 127.0.0.1 /empty.html                                                 0.991 ms - 20
[]
[2019-05-08T10:19:34.210+-200] HEAD    127.0.0.1       304 127.0.0.1 /empty.html                                                 0.927 ms - -
[]
[]
412 ifmatch "9699806-2168427-1557303462000"
412 etag "9699806-2170295-1557303591000"
412 caused by difference in size
412 caused by difference in modified
[2019-05-08T10:20:09.225+-200] PUT     127.0.0.1       412 127.0.0.1 /empty.html                                                 0.846 ms - -
[2019-05-08T10:20:14.619+-200] PUT                     - 127.0.0.1 /empty.html                                                 - ms - -
[]
[2019-05-08T10:20:14.628+-200] GET     127.0.0.1       200 127.0.0.1 /empty.html                                                 2.142 ms - 2170295
[]
[2019-05-08T10:20:14.771+-200] OPTIONS 127.0.0.1       200 127.0.0.1 /empty.html                                                 0.688 ms - 20
[]
[2019-05-08T10:20:14.772+-200] HEAD    127.0.0.1       304 127.0.0.1 /empty.html

**Comment by Arlen22** [comment] 2019-05-23 01:21
There is a difference in the file size, not just the date modified. I don’t know what would be causing this. Perhaps I’ll have to make a custom diff mode that highlights the differences in a file when there is an Etag error. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by MaruKob** [comment] 2019-05-23 07:29
Yes, but i think the difference at file and date is correct because i change tiddler.
I think the problem is , that the file on disk is different the file inside the browser because after a change in a tiddler the TW was automatically saved, but the browser do not noticed this change.

**Comment by Arlen22** [comment] 2019-05-23 07:37
But as long as there is only one browser tab open and it is only open on
one computer, then the browser is supposed to be made aware of the new file
size after it saves its changes. I will check into this and make sure that
this is not a bug in TiddlyServer somehow.

Can you tell me what version of TiddlyWiki the files are using?

**Comment by MaruKob** [comment] 2019-05-23 08:59
First 

Versions:

Tiddlyserver: v2.1.1-beta
TW: 5.1.19 and 5.1.14
Firefox: 66.0.5 (64-Bit)

**Comment by MaruKob** [comment] 2019-05-23 09:02
So if i do a change at Tiddler and close the Tiddler, the TW was correctly saved on disk, i tested.
The "Save-Button" stays on red.
If you now change any or same Tiddler the error came on close or if you hit the "save-Button"
If you reload (with a message of unwritten changes) all is fine to the next change.

I hope you understand my bad english

**Comment by Arlen22** [comment] 2019-05-23 09:06
Yes, I understand. TW 5.1.14 has a bug that must be fixed for each wiki, but 5.1.19 is supposed to work correctly. I will keep this open and investigate it.

**Comment by MaruKob** [comment] 2019-05-23 09:09
Error-msg:


XMLHttpRequest Fehler-Code: 412

and after click okay

Intern Javasript error
TypeError: xhr is undefined

**Comment by MaruKob** [comment] 2019-05-23 09:10
How fix i the bug?

Click on "Fix Put Saver Bookmarklet" and then import "updated Put Saver " ??

I do that, but it doesnt change anything

**Comment by Arlen22** [comment] 2019-05-23 09:21
That is for the bug in 5.1.14. This seems to be a different problem that you are experiencing now.

**Comment by MaruKob** [comment] 2019-05-23 09:24
Yes, i use the 5.1.14 too, so i fixed ist and testet again but it has no effect to the error

**Comment by ricardopretelt** [comment] 2019-05-25 14:56
I have the same error. When I modify a tiddler that existed before, it can overwrite the file but the browser does not recognize it. When I create a new tiddler I get the error XMLHttpRequest error code: 0
I am using TiddlyServer-2.1, tiddlywiki 5.1.19 and chrome. I am new to tiddlywiki but I really want it start with tiddlyserver.
Update: I don´t like to use extensions, so I could make it work with plain node.js but I really like your idea with tiddlyserver, hope I can help with something

**Comment by Arlen22** [comment] 2019-05-26 03:18
Ok, I think I found the problem. I pushed a fix to v2.1 branch. Please let me know if it works now. You can download the files as a zip file from the Github repo page.

**Comment by ricardopretelt** [comment] 2019-05-26 04:17
I did some tests and it is perfect.

**Comment by MaruKob** [comment] 2019-05-26 09:18
same here

thank you so much :D :D :D 

The Problem withe the "Save Button" is still alive, but not a problem for me now

best regards

**Comment by Arlen22** [comment] 2019-05-30 11:54
The save button problem is not related to TiddlyServer on single-file wikis. You can investigate it further on the TiddlyWiki user groups if you like.

**Closed as completed by Arlen22** 2019-05-30 11:54 UTC

**Comment by Marxsal** [comment] 2019-06-01 13:33
Which release or pre-release are we supposed to use? None of them seem to have an appropriate date stamp. Or just use the whole branch? Thanks!

**Comment by Arlen22** [comment] 2019-06-01 16:27
Just use branch v2.1 @ latest. v2.1 is the current master branch but I have
it named like this to keep it separate.
